
platform :ios, '8.0'
use_frameworks!

target 'SwiftCurrencyExchangeRate' do

pod 'SwiftyJSON', '~> 2.3.2'
pod 'Alamofire', '~> 3.4.0'
pod 'SnapKit', '~> 0.21.0'
pod 'AlamofireObjectMapper', '~> 3.0.0'
pod 'ObjectMapper', '~> 1.3.0'

end

